### ISSUE TITLE
Graceful exits for write timeouts?

### ISSUE THREAD

**Issue by cybrox** [CrowdHailer/Ace#113]
Hi. First of all, thanks for building and maintaining raxx/ace! It helped me a ton implementing behaviours where plug/cowboy are too restrictive.

When continuously sending a response, I noticed that the worker crashes when it is unable to send more data. This is especially prone to happen when a device switches between different networks or loses network connection without the TCP connection being closed properly. The cause of the crash is, that [this code](https://github.com/CrowdHailer/Ace/blob/master/lib/ace/http/channel.ex#L47-L56) only checks if the listener has already been terminated but doesn't handle timeouts.

<details><summary>The resulting error</summary>
<pre>
[error] GenServer #PID<0.780.0> terminating
** (stop) exited in: GenServer.call(#PID<0.578.0>, {:send, %Ace.HTTP.Channel{endpoint: #PID<0.578.0>, id: 1, socket: {:tcp, #Port<0.78488>}}, [%Raxx.Data{data: <<13, 10, 45, 45, 102, 102, 115, 101, 114, 118, 101, 114, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 116, 121, 112, 101, 58, 32, 105, 109, 97, 103, 101, 47, 106, 112, 101, 103, 13, 10, 67, 111, 110, 116, 101, ...>>}]}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:831: GenServer.call/3
    (ace) lib/ace/http/channel.ex:48: Ace.HTTP.Channel.send/2
    (ace) lib/ace/http/worker.ex:88: Ace.HTTP.Worker.do_send/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :send_dummy_frame
State: %Ace.HTTP.Worker{app_module: WheatleyWeb.Router, app_state: %{frame_id: 12}, channel: %Ace.HTTP.Channel{endpoint: #PID<0.578.0>, id: 1, socket: {:tcp, #Port<0.78488>}}, channel_monitor: #Reference<0.3214544271.3276275716.8929>}


[error] GenServer #PID<0.578.0> terminating
** (stop) exited in: GenServer.call(#PID<0.578.0>, {:send, %Ace.HTTP.Channel{endpoint: #PID<0.578.0>, id: 1, socket: {:tcp, #Port<0.78488>}}, [%Raxx.Data{data: <<13, 10, 45, 45, 102, 102, 115, 101, 114, 118, 101, 114, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 116, 121, 112, 101, 58, 32, 105, 109, 97, 103, 101, 47, 106, 112, 101, 103, 13, 10, 67, 111, 110, 116, 101, ...>>}]}, 5000)
    ** (EXIT) time out
Last message: {:DOWN, #Reference<0.3214544271.3276275716.8930>, :process, #PID<0.780.0>, {:timeout, {GenServer, :call, [#PID<0.578.0>, {:send, %Ace.HTTP.Channel{endpoint: #PID<0.578.0>, id: 1, socket: {:tcp, #Port<0.78488>}}, [%Raxx.Data{data: <<13, 10, 45, 45, 102, 102, 115, 101, 114, 118, 101, 114, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 116, 121, 112, 101, 58, 32, 105, 109, 97, 103, 101, ...>>}]}, 5000]}}}
State: %Ace.HTTP1.Endpoint{channel: %Ace.HTTP.Channel{endpoint: #PID<0.578.0>, id: 1, socket: {:tcp, #Port<0.78488>}}, keep_alive: false, monitor: #Reference<0.3214544271.3276275716.8930>, receive_state: {:done, "", %{max_line_length: 2048}}, socket: {:tcp, #Port<0.78488>}, status: {:request, :chunked_body}, worker: #PID<0.780.0>}


[error] GenServer #PID<0.578.0> terminating
** (stop) exited in: GenServer.call(#PID<0.578.0>, {:send, %Ace.HTTP.Channel{endpoint: #PID<0.578.0>, id: 1, socket: {:tcp, #Port<0.78488>}}, [%Raxx.Data{data: <<13, 10, 45, 45, 102, 102, 115, 101, 114, 118, 101, 114, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 116, 121, 112, 101, 58, 32, 105, 109, 97, 103, 101, 47, 106, 112, 101, 103, 13, 10, 67, 111, 110, 116, 101, ...>>}]}, 5000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:726: :gen_server.handle_common_reply/8
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.577.0>): {:accept, {:tcp, #Port<0.78384>}}
State: %Ace.HTTP.Server{settings: [port: 8444, cleartext: true], socket: nil, worker_supervisor: #PID<0.574.0>}
Client #PID<0.577.0> is alive
    (stdlib) gen_server.erl:381: :gen_server.loop/7
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
</pre>
</details>

     
---
I was not sure if this is intended, because it is kind of reasonable that a worker dies when it encounters an error such as not being able to send its response but on the other hand, I think it is more reasonable to catch this and allow the user to handle it (e.g. shut down the worker gracefully)

This is my current forked workaround implementation
```elixir
 def send(channel = %__MODULE__{}, parts) do
    GenServer.call(channel.endpoint, {:send, channel, parts})
  catch
    :exit, {reason, _details} ->
      # handle the :reason here
      {:error, :connection_closed}
  end
```

Is the crashing behaviour intended or would a PR to improve timeout handling be welcome?

**Comment by CrowdHailer** [comment]
It's an interesting question. I wan't the server process to exit in the case that the it is unable to connect with the socket. I think it is a good design goal to have any state that needs to last longer than the connection be moved out of the worker.

However looking at the code snippet I see we already catch the no_proc case

Improving timeout handling would be welcome.

**Comment by cybrox** [comment]
@CrowdHailer Yep! Tried it in the actual app and there is no more errors on timeout, workers are shutting down as expected now!
Also, thanks for the references in the patch, very interesting read.
