### ISSUE TITLE
State between requests?

### ISSUE THREAD

**Issue by squarism** [CrowdHailer/Ace#121]
I understand how to set up a supervisor, set defaults and get the state within an endpoint.  It took a bit of fiddling, maybe it's obvious to experienced Elixir devs.  I'm trying to understand what `state` is doing and if I should be messing with it.  I can definitely set up defaults in a `mix new --sup` type app:

```
# lib/application.ex
...
def start(_type, _args) do
    children = [
      {MyApp, []},   # <-- here is the default state
```

But it seems like state is used internally?  Ok, so if I want things to survive between requests (imagine a counter), should I just spin up another GenServer/Agent?  Does Ace not speak to this problem (not in criticism but in design)?

Is state just for app defaults maybe, like the README says for `greeting: "Hello"`.  So it can't be mutated (or returned really).

**Comment by squarism** [comment]
I got something working using a simple Agent.  I keep "app state" out of Ace's boundaries and it seems to work just fine.  It's just vanilla Elixir really.  Sorry for using issues for help but I thought it might be useful for future searches.

**Comment by CrowdHailer** [comment]
Sure no problem. Probably a better forum for questions is  the slack channel, more people are likely to try and offer an answer there. https://elixir-lang.slack.com/messages/C56H3TBH8/

You more or less have the answer, state only lasts the duration of a request/response, it can change but only in the case of streaming, in which case the request response lives longer
If you think it warrants it could you add this particular question to the Raxx FAQ. (we should probably add a link from the Ace project to Raxx FAQ)
