### ISSUE TITLE
:elixir_errors.warn/3 no longer exists

### ISSUE THREAD

**Issue by lasseebert** [CrowdHailer/Ace#137]
From Elixir 1.8.2 to Elixir 1.9.0, `:elixir_errors.warn/3` was renamed to `:elixir_errors.erl_warn/3`, ref: https://github.com/elixir-lang/elixir/commit/0ce62a2add91e6a942b89430738f77062365b4e8#diff-ed0a878a29a4e0266095d1153c4f3a00L8-R8

This gives a warning in my project, since it is used in Ace.HTTP.Service: https://github.com/CrowdHailer/Ace/blob/0dca87887c279fdb77fe669ebab2db05330c995e/lib/ace/http/service.ex#L71 (inside quote in `__using__`).

I'm not sure why `:elixir_errors` is called directly, which is why I'm not submitting a PR. I think it can be replaced with `IO.warn/2`.

**Comment by CrowdHailer** [comment]
There's no reason `:elixir_errors` is used directly.
