### ISSUE TITLE
Performance measurement

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/Ace#30]
Mention Tobias

**Comment by CrowdHailer** [comment]
nice to have later

**Comment by CharlesOkwuagwu** [comment]
A simple measure could be timing on request/response execution.

One simple way of adding this is: [elli TIMING HELPERS](https://github.com/knutin/elli/blob/master/src/elli_http.erl#L609-L628)

**Comment by CrowdHailer** [comment]
Closed because I'm not looking to take tackle this soon. however if it's something you want to look into PR's be very welcome
