### ISSUE TITLE
Accessing connection PIDs

### ISSUE THREAD

**Issue by Paul-Cockrell** [CrowdHailer/Ace#31]
Is there a way to retrieve the current client connection PID in the handle_connect function so it can be put in the state variable, as I need to be able to be able to make use of it later to be able to send messages from the server to specific clients on demand, not simply reply to clients in reaction to incoming messages.

Apologies if this is not the right place to ask a question.

**Comment by CrowdHailer** [comment]
Not 100% what you are asking, there is not really a PID that should be exposed for sending messages. You can return a value to be sent at the end of a handle_info callback. 

Could you perhaps write some example code of what you would expect to see?
