### ISSUE TITLE
Ace.HTTP explodes on absolute URLs

### ISSUE THREAD

**Issue by samphilipd** [CrowdHailer/Ace#42]
See stacktrace:

```
Elixir.CaseClauseError

no case clause matching: {:ok, {:http_request, :GET, {:absoluteURI, :http, "localhost", :undefined, "/status"}, {1, 1}}, "User-Agent: check_http/v2.1.2 (monitoring-plugins 2.1.2)\r\nConnection: close\r\nHost: localhost:3006\r\nUser-Agent: Nested-Internal-HealthChecker\r\n\r\n"}
```

Note:

code is here https://github.com/CrowdHailer/Ace/blob/338775da892c7aafc7959d6a7d7a3564ff8d7416/extensions/http(s)/lib/ace/http/handler.ex#L70

 
would need to handle the remaining cases here http://erlang.org/doc/man/erlang.html#decode_packet-3 in the case clause.

**Comment by CrowdHailer** [comment]
Could you open up a PR which has failing test cases that demonstrate this error

**Comment by samphilipd** [comment]
@CrowdHailer sure thing! Can you give me any guidance as to which test file it should go in?

**Comment by CrowdHailer** [comment]
It should go in request test https://github.com/CrowdHailer/Ace/blob/0.9.x/extensions/http(s)/test/ace/http/request_test.exs

Also please branch off the 0.9.x branch

**Comment by CrowdHailer** [comment]
https://hex.pm/packages/ace_http `version 0.4.6` available
