### ISSUE TITLE
Ace.HTTP should return 400 if request is missing or has invalid/multiple Host header

### ISSUE THREAD

**Issue by samphilipd** [CrowdHailer/Ace#46]
See: https://tools.ietf.org/html/rfc7230#section-5.4

**Comment by CrowdHailer** [comment]
Sounds like the behaviour is more or less clear hear. I think no Host header is allowed if making a HTTP/1.0 request but as I am now working on 2.0 im not sure I am bothered about supporting pre 1.1

Looks like this just needs two test cases

**Comment by CrowdHailer** [comment]
Any progress on this one?

**Comment by CrowdHailer** [comment]
Tempted to close this as host is one of the "special headers" in HTTP/2 and can just be tackled when we merge ace_http and ace. Unless @samphilipd you require this now, in which case it can be added to ace_http ahead of the merge

**Comment by samphilipd** [comment]
@crowdhailer Nope don't require this now.
