### ISSUE TITLE
Clarify `state` in `Ace.HTTP.Server` 

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [CrowdHailer/Ace#70]
https://github.com/CrowdHailer/Ace/blob/e39bfbf5a99dde225d3adcf680885e0bd71a86a4/lib/ace/http/server.ex#L51-L68

Is the `state` from Line:51 the same state that's being overwritten on line on Line:59? 

If yes, then line Line:55 is unnecessary ... same appears again further down.
This would also make `:socket` unnecessary in  `defstruct [:worker_supervisor, :settings, :socket]`

**Comment by CrowdHailer** [comment]
A cursory glance suggests line 55 is unnecessary. I can't explicitly remember typing that line. I would just delete it and check all the tests pass. 

If doing so introduces a bug but no test fails then we discover a new test that needs writing

**Comment by CrowdHailer** [comment]
Did you try the tests with this line deleted

**Comment by CharlesOkwuagwu** [comment]
Yes. It works the same with that line commented out.
